version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      python-all:
        patterns:
          - "*"
